Updated powerlevel10k

diff --git a/zsh-custom/themes/powerlevel10k/gitstatus/install b/zsh-custom/themes/powerlevel10k/gitstatus/install
--- a/zsh-custom/themes/powerlevel10k/gitstatus/install
+++ b/zsh-custom/themes/powerlevel10k/gitstatus/install
@@ -9,17 +9,17 @@ _gitstatus_install_main() {
     set -u
   fi
 
-  local argv1=$1
+  local argv1="$1"
   shift
 
-  local no_check= no_install= uname_s= uname_m= gitstatus_dir=
+  local no_check= no_install= uname_s= uname_m= gitstatus_dir= dl_status=
   local opt= OPTARG= OPTIND=1
 
-  while getopts ':s:m:d:fnh' opt "$@"; do
+  while getopts ':s:m:d:p:fnh' opt "$@"; do
     case "$opt" in
       h)
         command cat <<\END
-Usage: install [-s KERNEL] [-m ARCH] [-d DIR] [-f|-n] [-- CMD [ARG]...]
+Usage: install [-s KERNEL] [-m ARCH] [-d DIR] [-p CMD] [-f|-n] [-- CMD [ARG]...]
 
 If positional arguments are specified, call this on success:
 
@@ -35,6 +35,7 @@ Options:
   -s KERNEL  use this instead of lowercase `uname -s`
   -m ARCH    use this instead of lowercase `uname -m`
   -d DIR     use this instead of `dirname "$0"`
+  -p CMD     eval this every second while downloading gitstatusd
   -f         download gitstatusd even if there is one locally
   -n         do not download gitstatusd (fail instead)
 END
@@ -64,6 +65,17 @@ END
           return 1
         fi
         gitstatus_dir="$OPTARG"
+      ;;
+      p)
+        if [ -n "$dl_status" ]; then
+          >&2 echo "[gitstatus] error: duplicate option: -$opt"
+          return 1
+        fi
+        if [ -z "$OPTARG" ]; then
+          >&2 echo "[error] incorrect value of -$opt: $OPTARG"
+          return 1
+        fi
+        dl_status="$OPTARG"
       ;;
       m)
         if [ -n "$uname_m" ]; then
@@ -147,10 +159,14 @@ END
     line="${line###*}"
     [ -n "$line" ] || continue
 
-    local uname_s_glob= uname_m_glob= file= version=
+    local uname_s_glob= uname_m_glob= file= version= sha256=
     eval "$line" || return
 
-    if [ -z "$uname_s_glob" -o -z "$uname_m_glob" -o -z "$file" -o -z "$version" ]; then
+    if [ -z "$uname_s_glob" -o \
+         -z "$uname_m_glob" -o \
+         -z "$file"         -o \
+         -z "$version"      -o \
+         -z "$sha256" ]; then
       >&2 echo "[gitstatus] internal error: invalid install.info line: $line"
       return 1
     fi
@@ -204,61 +220,199 @@ END
     fi
     [ -d "$cache_dir" ] || mkdir -p -- "$cache_dir" || return
 
-    local url="https://github.com/romkatv/gitstatus/releases/download/$version/$file.tar.gz"
-    local archive="$cache_dir"/"$file".tmp.$$.tar.gz
-    if command -v curl >/dev/null 2>&1; then
-      if ! err="$(command curl -fsSLo "$archive" -- "$url" 2>&1)"; then
-        >&2 echo "[gitstatus] error: failed to download gitstatusd: $url"
-        >&2 printf "%s\n" "$err"
-        return 1
-      fi
-    elif command -v wget >/dev/null 2>&1; then
-      if ! err="$(command wget -O "$archive" -- "$url" 2>&1)"; then
-        >&2 echo "[gitstatus] error: failed to download gitstatusd: $url"
-        >&2 printf "%s\n" "$err"
-        return 1
-      fi
-    else
+    local tmpdir
+    if ! command -v mktemp >/dev/null 2>&1 ||
+        ! tmpdir="$(command mktemp -d "${TMPDIR:-/tmp}"/gitstatus-install.XXXXXXXXXX)"; then
+      tmpdir="${TMPDIR:-/tmp}/gitstatus-install.tmp.$$"
+      mkdir -p -- "$tmpdir" || return
+    fi
+
+    if ! command -v curl >/dev/null 2>&1 && ! command -v wget >/dev/null 2>&1; then
       >&2 echo "[gitstatus] error: please install curl or wget"
       return 1
     fi
 
     (
-      if [ -n "${ZSH_VERSION:-}" ]; then
-        builtin cd -q -- "$cache_dir" || return
-      else
-        cd -- "$cache_dir" || return
-      fi
-
-      local old=
-      if [ -e "$daemon" ]; then
-        local i=1
-        while :; do
-          old="$daemon"."$i"
-          [ -e "$old" ] || break
-          i="$((i+1))"
-        done
-        command mv -f -- "$daemon" "$old" || return
-      fi
-
-      command tar -xzf "$archive"
-      local ret=$?
-      command rm -f -- "$archive"
-      if [ -n "$old" ]; then
+      run_cmd() {
+        command -v "$1" >/dev/null 2>/dev/null || return 127
+        local trapped= pid die ret
+        trap 'trapped=1' $sig
+        # The only reason for suppressing stderr is that `curl -f` cannot be silenced:
+        # `-s` doesn't work despite what the docs say.
+        command "$@" 2>/dev/null &
+        ret="$?"
         if [ "$ret" = 0 ]; then
-          command rm -f -- "$old" 2>/dev/null
-        else
-          command mv -f -- "$old" "$daemon"
+          pid="$!"
+          die="trap - $sig; kill -- $pid 2>/dev/null; wait -- $pid 2>/dev/null; exit 1"
+          trap "$die" $sig
+          [ -z "$trapped" ] || eval "$die"
+          wait -- "$pid" 2>/dev/null
+          ret="$?"
         fi
+        trap - $sig
+        [ -z "$trapped" ] || exit
+        return "$ret"
+      }
+
+      check_sha256() {
+        local data_file="$tmpdir"/"$1".tar.gz
+        local hash_file="$tmpdir"/"$1".tar.gz.sha256
+        local hash=
+        if command -v shasum >/dev/null 2>/dev/null; then
+          if run_cmd shasum -b -a 256 -- "$data_file" >"$hash_file"; then
+            IFS= read -r hash <"$hash_file" || hash=
+            hash="${hash%% *}"
+          fi
+        elif command -v sha256sum >/dev/null 2>/dev/null; then
+          if run_cmd sha256sum -b -- "$data_file" >"$hash_file"; then
+            IFS= read -r hash <"$hash_file" || hash=
+            hash="${hash%% *}"
+          fi
+        elif command -v sha256 >/dev/null 2>/dev/null; then
+          if run_cmd sha256 -- "$data_file" </dev/null >"$hash_file"; then
+            IFS= read -r hash <"$hash_file" || hash=
+            # Ignore sha256 output if it's from hashalot. It's incompatible.
+            if [ ${#hash} -lt 64 ]; then
+              hash=
+            else
+              hash="${hash##* }"
+            fi
+          fi
+        fi
+        [ "$1" = 1 -a -z "$hash" -o "$hash" = "$sha256" ]
+      }
+
+      local url1="https://github.com/romkatv/gitstatus/releases/download/$version/$file.tar.gz"
+      local url2="https://gitee.com/romkatv/gitstatus/raw/release-$version/release/$file.tar.gz"
+      local sig='INT QUIT TERM ILL PIPE'
+
+      fetch() {
+        if [ "$1" != 1 ] && command -v sleep >/dev/null 2>/dev/null; then
+          if ! run_cmd sleep "$1"; then
+            echo -n >"$tmpdir"/"$1".status
+            return 1
+          fi
+        fi
+        local cmd part url ret
+        for cmd in 'curl -q -fsSL' 'wget --no-config -qO-'; do
+          part=0
+          while true; do
+            if [ "$part" = 2 ]; then
+              ret=1
+              break
+            elif [ "$part" = 0 ]; then
+              url="$2"
+            else
+              url="$2"."$part"
+            fi
+            run_cmd $cmd -- "$url" >>"$tmpdir"/"$1".tar.gz
+            ret="$?"
+            [ "$ret" = 0 ] || break
+            check_sha256 "$1" && break
+            part=$((part+1))
+          done
+          [ "$ret" = 0 ] && break
+          run_cmd rm -f -- "$tmpdir"/"$1".tar.gz && continue
+          ret="$?"
+          break
+        done
+        echo -n >"$tmpdir"/"$1".status
+        return "$ret"
+      }
+
+      local trapped=
+      trap 'trapped=1' $sig
+      fetch 1 "$url1" & 
+      local pid1="$!"
+      fetch 2 "$url2" & 
+      local pid2="$!"
+
+      local die="trap - $sig; kill -- $pid1 $pid2 2>/dev/null; wait -- $pid1 $pid2 2>/dev/null; exit 1"
+      trap "$die" $sig
+      [ -z "$trapped" ] || eval "$die"
+
+      local n=
+      while true; do
+        [ -z "$dl_status" ] || eval "$dl_status" || eval "$die"
+        if command -v sleep >/dev/null 2>/dev/null; then
+          command sleep 1
+        elif command -v true >/dev/null 2>/dev/null; then
+          command true
+        fi
+        if [ -n "$pid1" -a -e "$tmpdir"/1.status ]; then
+          wait -- "$pid1" 2>/dev/null
+          local ret="$?"
+          pid1=
+          if [ "$ret" = 0 ]; then
+            if [ -n "$pid2" ]; then
+              kill -- "$pid2" 2>/dev/null
+              wait -- "$pid2" 2>/dev/null
+            fi
+            n=1
+            break
+          elif [ -z "$pid2" ]; then
+            break
+          else
+            die="trap - $sig; kill -- $pid2 2>/dev/null; wait -- $pid2 2>/dev/null; exit 1"
+            trap "$die" $sig
+          fi
+        elif [ -n "$pid2" -a -e "$tmpdir"/2.status ]; then
+          wait -- "$pid2" 2>/dev/null
+          local ret="$?"
+          pid2=
+          if [ "$ret" = 0 ]; then
+            if [ -n "$pid1" ]; then
+              kill -- "$pid1" 2>/dev/null
+              wait -- "$pid1" 2>/dev/null
+            fi
+            n=2
+            break
+          elif [ -z "$pid1" ]; then
+            break
+          else
+            die="trap - $sig; kill -- $pid1 2>/dev/null; wait -- $pid1 2>/dev/null; exit 1"
+            trap "$die" $sig
+          fi
+        fi
+      done
+
+      trap - $sig
+
+      if [ -z "$n" ]; then
+        >&2 echo "[gitstatus] error: failed to download gitstatusd from any mirror"
+        >&2 echo ""
+        >&2 echo "  1. $url1"
+        >&2 echo "  2. $url2"
+        exit 1
       fi
-      exit "$ret"
-    ) || return
+
+      command tar -C "$tmpdir" -xzf "$tmpdir"/"$n".tar.gz || exit
+
+      local tmpfile
+      if ! command -v mktemp >/dev/null 2>&1 ||
+         ! tmpfile="$(command mktemp "$cache_dir"/gitstatusd.XXXXXXXXXX)"; then
+        tmpfile="$cache_dir"/gitstatusd.tmp.$$
+      fi
+
+      command mv -f -- "$tmpdir"/gitstatusd-* "$tmpfile" || exit
+      command mv -f -- "$tmpfile" "$cache_dir"/"$file" && exit
+      command rm -f -- "$cache_dir"/"$file"
+      command mv -f -- "$tmpfile" "$cache_dir"/"$file" && exit
+      command rm -f -- "$tmpfile"
+      exit 1
+    )
+
+    local ret="$?"
+    command rm -rf -- "$tmpdir"
+    [ "$ret" = 0 ] || return
 
     [ $# = 0 ] || "$@" "$daemon" "$version" 1
     return
   done <"$gitstatus_dir"/install.info
 
   >&2 echo "[gitstatus] error: no gitstatusd found for $uname_s $uname_m"
+  >&2 echo ""
+  >&2 echo "See: https://github.com/romkatv/gitstatus/blob/master/README.md#compiling"
   return 1
 }
 
diff --git a/zsh-custom/themes/powerlevel10k/gitstatus/mbuild b/zsh-custom/themes/powerlevel10k/gitstatus/mbuild
--- a/zsh-custom/themes/powerlevel10k/gitstatus/mbuild
+++ b/zsh-custom/themes/powerlevel10k/gitstatus/mbuild
@@ -46,7 +46,7 @@
 #     ps> C:\msys64\autorebase.bat
 # - Install 64-bit and 32-bit cygwin: https://cygwin.com/install.html.
 #   - Choose to install 32-bit to c:/cygwin32 instead of the default c:/cygwin.
-#   - Select these packages: binutils, cmake, gcc-core, gcc-g++, git, make, wget.
+#   - Select these packages: binutils, cmake, gcc-core, gcc-g++, git, make, perl, wget.
 #
 # IMPORTANT: Install msys2 and cygwin one at a time.
 #
@@ -151,7 +151,7 @@ done
 
 shift $((OPTIND - 1))
 
-(( $# )) || set -- ${(k)assets}
+(( $# )) || set -- ${(ko)assets}
 set -- ${(u)@}
 
 local platform
@@ -200,15 +200,22 @@ function build-windows() {
 
   local tmp env bin intro flags=(-w)
   case $2 in
-    msys_nt-10.0-i686)     bin='msys32/usr/bin';|
-    msys_nt-10.0-x86_64)   bin='msys64/usr/bin';|
     cygwin_nt-10.0-i686)   bin='cygwin32/bin'  ;|
     cygwin_nt-10.0-x86_64) bin='cygwin64/bin'  ;|
+    msys_nt-10.0-i686)     bin='msys32/usr/bin';|
+    msys_nt-10.0-x86_64)   bin='msys64/usr/bin';|
+    cygwin_nt-10.0-*)
+      tmp='/cygdrive/c/tmp'
+    ;|
     msys_nt-10.0-*)
       flags+=(-s)
       tmp='/c/tmp'
       env='MSYSTEM=MSYS'
+      intro='pacman -Syu --noconfirm; pacman -S --needed --noconfirm git; '
+      intro+='PATH="$PATH:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"'
       while true; do
+        # TODO: run autorebase only when getting an error that can be fixed by autorebasing.
+        break
         local out
         out="$(ssh $1 cmd.exe "$c/${bin%%/*}/autorebase.bat" 2>&1)"
         [[ $out == *"The following DLLs couldn't be rebased"* ]] || break
@@ -243,12 +250,7 @@ function build-windows() {
           }
         done
       } "$@"
-      intro='pacman -Syu --noconfirm; pacman -S --needed --noconfirm git; '
-      intro+='PATH="$PATH:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"'
-    ;;
-    cygwin_nt-10.0-*)
-      tmp='/cygdrive/c/tmp'
-    ;;
+    ;|
   esac
 
   ssh $1 $c/$bin/env.exe $env c:/$bin/bash.exe -l <<<"
@@ -281,17 +283,24 @@ function mbuild() {
     print -r -- "starting build for $platform on $assets[$platform] (pid $!)"
     pids+=($platform $!)
   done
+  local failed=()
   for platform pid in $pids; do
     print -rn -- "$platform => "
     if wait $pid; then
       print -r -- "ok"
     else
-      print -r -- "error $?"
-      print -r -- "---------------------"
-      >&2 cat $logs/$platform
-      return 1
+      print -r -- "error"
+      failed+=$platform
     fi
   done
+  (( $#failed )) || return 0
+  print
+  print -r -- "Error logs:"
+  print
+  for platform in $failed; do
+    print -r -- "  $platform => $logs/$platform"
+  done
+  return 1
 }
 
 # Copied from https://github.com/romkatv/run-process-tree.
